title: ember-cordova
description: "Documentation for corber, a CLI for packaging hybrid Cordova/Crosswalk/Phonegap apps with Ember/Vue/Webpac/Glimmer"
author: Isle of Code
url: "http://corber.io"
baseurl: ''
twitter_username: isleOfCode
github_username:  isleOfCode
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: none

highlighter: rouge

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true
